### ISSUE TITLE
Зачем такая сложная логика добавления сервлетов?

### ISSUE THREAD

**Issue by oxeg** [java-park-mail-ru/2016-02-X-O#3]
Почему нельзя было просто добавить 2 сервлета в contextHandler?
Зачем такая сложная логика с итераторами и декораторами?

**Comment by KasyanDiGris** [comment]
Егор, я рассчитываю вынести большинство настроек сервера в отдельный модуль. С таким подходом можно описать в ресурсном файле урл и необходимые декораторы для сервлета и при инициализации сервера использовать уже наполненный ServletManager.
Декораторы нужны, чтобы в каждом методе не пришлось проверять авторизацию пользователя.
